name: Kick Nuke Bot

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env
        run: |
          echo "KICK_CLIENT_ID=01KA74G87R28Q8WV5VRN1R5HGH" >> .env
          echo "KICK_CLIENT_SECRET=3b6818ae5c89a9477b332f560b7958982ba668b31cc5647e2da4b29d08903253" >> .env
          echo "KICK_REDIRECT_URI=http://127.0.0.1.nip.io/callback" >> .env
          echo "KICK_CHANNELS=bruhin" >> .env

      - name: Generate OAuth link
        run: |
          python auth_bot.py

      - name: Run bot FOREVER
        run: |
          echo "=== START BOT LOOP ==="
          while true
          do
            python nuke_bot.py || true
            echo "[BOT] Restart in 5s..."
            sleep 5
          done
