name: Kick Nuke Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"   

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env file IN REPO
        run: |
          echo "KICK_CLIENT_ID=${{ secrets.KICK_CLIENT_ID }}" >> $GITHUB_WORKSPACE/.env
          echo "KICK_CLIENT_SECRET=${{ secrets.KICK_CLIENT_SECRET }}" >> $GITHUB_WORKSPACE/.env
          echo "KICK_REDIRECT_URI=${{ secrets.KICK_REDIRECT_URI }}" >> $GITHUB_WORKSPACE/.env
          echo "KICK_CHANNELS=${{ secrets.KICK_CHANNELS }}" >> $GITHUB_WORKSPACE/.env
          echo "--- ENV CREATED IN REPO ---"
          cat $GITHUB_WORKSPACE/.env

      - name: Generate OAuth link
        run: |
          python auth_bot.py

      - name: Run bot FOREVER
        run: |
          while true
          do
            python nuke_bot.py
            echo "[BOT] Restart in 5s..."
            sleep 5
          done
