name: Kick Nuke Bot

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-dotenv
          pip install -r requirements.txt

      - name: Create .env file
        run: |
          echo "KICK_CLIENT_ID=${{ secrets.KICK_CLIENT_ID }}" > .env
          echo "KICK_CLIENT_SECRET=${{ secrets.KICK_CLIENT_SECRET }}" >> .env
          echo "KICK_REDIRECT_URI=${{ secrets.KICK_REDIRECT_URI }}" >> .env
          echo "KICK_CHANNELS=${{ secrets.KICK_CHANNELS }}" >> .env

      - name: Generate OAuth link
        run: |
          python auth_bot.py

      - name: Run bot FOREVER
        run: |
          echo "=== START BOT LOOP ==="
          while true
          do
            python nuke_bot.py
            echo "Restart in 5s..."
            sleep 5
          done
